import type {Metadata} from "next";
import "./globals.css";
import localFont from "next/font/local";
import MenuBar from "@/app/menubar";
import Footer from "@/app/footer";

const StudioFeixenEdgy = localFont({src: '../../public/fonts/StudioFeixenEdgyVFTRIALGX.ttf',})

export const metadata: Metadata = {
    title: "Atishay Jain",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="font-config">
        <body className={StudioFeixenEdgy.className}>
        <div className="w-screen min-h-screen flex flex-col justify-between">
        <div className="container p-0 items-center justify-center mt-14">
            <MenuBar/>
            <div className="z-0">
                {children}
            </div>
        </div>
            <Footer/>
            </div>
        </body>
        </html>
    );
}
